baseURL = "https://nayami.org/"
languageCode = "ja"
title = "若きガイジンの悩み"
defaultContentLanguage = "ja"
theme = "archie"
copyright = "uncomputable"

[params]
mode="toggle"   # color-mode → light,dark,toggle or auto
useCDN=false    # don't use CDNs for fonts and icons, instead serve them locally.
#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
mathjax = false # enable MathJax support
katex = false   # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/uncomputable/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://nayami.org/index.xml"

[outputs]
home = ['html', 'rss']

[[menu.main]]
name = "ホーム"
url = "/"
weight = 1

[[menu.main]]
name = "すべての投稿"
url = "/posts"
weight = 2

[[menu.main]]
name = "私について"
url = "/about"
weight = 3

[[menu.main]]
name = "タグ"
url = "/tags"
weight = 4

[[menu.main]]
name = "お問い合わせ"
url = "/contact"
weight = 5
